/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPortEvent;
import gnu.io.*;
import gnu.io.SerialPortEventListener;
import java.io.BufferedReader;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.sql.rowset.serial.SerialArray;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Comunica extends javax.swing.JFrame implements SerialPortEventListener {

    ////////variaveis//////////
    private String[] PORT_NAME_LIST; // Retorna o nome das portas disponiveis 
    private Enumeration BUSCA_LISTA_PORTA; // Retorna a listas disponiveis no sistema 
    private CommPortIdentifier ID_Porta; // retorna o ID da porta
    private SerialPort SERIAL_PORT;
    private final String appName = "serialCNC";
    private final int TIME_OUT = 1000;
    private OutputStream output = null;
    private BufferedReader input = null;
    private String SERIAL_PORT_NAME;
    private int BAULD_RATES;

    /**
     * Creates new form Comunica
     */
    public Comunica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Bauld_Rates = new javax.swing.JComboBox<>();
        jComboBox_Portas = new javax.swing.JComboBox<>();
        jComboBox_Modelo_Placa = new javax.swing.JComboBox<>();
        txt_Status = new javax.swing.JTextField();
        lbl_Imagem_conexao = new javax.swing.JLabel();
        btn_Inicio = new javax.swing.JButton();
        btn_Conectar = new javax.swing.JButton();
        btn_Desconectar = new javax.swing.JButton();
        lbl_Led_Status = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comunicação");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modelo Placa:");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Velocidade:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Status:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Portas:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBox_Bauld_Rates.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_Portas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox_Modelo_Placa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Status.setEditable(false);
        txt_Status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Status.setForeground(new java.awt.Color(255, 0, 0));
        txt_Status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Status.setText("Desconectado");
        txt_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_StatusActionPerformed(evt);
            }
        });

        lbl_Imagem_conexao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Imagem_conexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Imagem_conexao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Inicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Inicio.setText("Buscar portas");
        btn_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InicioActionPerformed(evt);
            }
        });

        btn_Conectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Conectar.setText("Conectar");
        btn_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConectarActionPerformed(evt);
            }
        });

        btn_Desconectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Desconectar.setText("Desconectar");
        btn_Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DesconectarActionPerformed(evt);
            }
        });

        lbl_Led_Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Led_Status.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Imagem_conexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Bauld_Rates, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Portas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Led_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addComponent(jComboBox_Modelo_Placa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Inicio)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Conectar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Desconectar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Modelo_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Bauld_Rates, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Portas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Led_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Status, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Imagem_conexao, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InicioActionPerformed
        jComboBox_Portas.setModel(new DefaultComboBoxModel(new String[]{}));
        jComboBox_Bauld_Rates.setModel(new DefaultComboBoxModel(new String[]{}));

        RetornaPortas();

        for (int i = 0; i < PORT_NAME_LIST.length; i++) {

            if (PORT_NAME_LIST[i] != null) {
                jComboBox_Portas.addItem(PORT_NAME_LIST[i]);
                Bauld_Rates();
                lbl_Imagem_conexao.setText("Set os valores e click em Conectar!");
            }
            if (PORT_NAME_LIST[0] == null) {
                lbl_Imagem_conexao.setText("Nenhuma porta emcontrada!");
            }

        }


    }//GEN-LAST:event_btn_InicioActionPerformed

    private void btn_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConectarActionPerformed
       SERIAL_PORT_NAME = (String)(jComboBox_Portas.getSelectedItem());
        BAULD_RATES = (int)(jComboBox_Bauld_Rates.getSelectedIndex());
        
        if(iniciaSerial(SERIAL_PORT_NAME, BAULD_RATES)){
            
             txt_Status.setText("Conectado !");
             lbl_Imagem_conexao.setText("");
        
        }
        
    }//GEN-LAST:event_btn_ConectarActionPerformed

    private void btn_DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DesconectarActionPerformed
        fechaSerial();
               
    }//GEN-LAST:event_btn_DesconectarActionPerformed

    private void txt_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StatusActionPerformed

    //////////////////Funçoes //////////////////////////
    //Retorna portas disponiveis
    public String[] RetornaPortas() {
        int i = 0;

        BUSCA_LISTA_PORTA = null;
        BUSCA_LISTA_PORTA = CommPortIdentifier.getPortIdentifiers();
        PORT_NAME_LIST = new String[10];

        while (BUSCA_LISTA_PORTA.hasMoreElements()) {
            CommPortIdentifier PORTA_ATUAL = (CommPortIdentifier) BUSCA_LISTA_PORTA.nextElement();
            PORT_NAME_LIST[i] = PORTA_ATUAL.getName();
            i++;

        }

        return PORT_NAME_LIST;
    }

    private void Bauld_Rates() {
        jComboBox_Bauld_Rates.addItem("300");
        jComboBox_Bauld_Rates.addItem("1200");
        jComboBox_Bauld_Rates.addItem("2400");
        jComboBox_Bauld_Rates.addItem("9600");
        jComboBox_Bauld_Rates.addItem("19200");
        jComboBox_Bauld_Rates.addItem("38400");
        jComboBox_Bauld_Rates.addItem("57600");
        jComboBox_Bauld_Rates.addItem("115200");
        jComboBox_Bauld_Rates.addItem("230400");
        jComboBox_Bauld_Rates.addItem("250000");

    }

    public boolean iniciaSerial(String serial_port, int bauld_rate) {

        boolean status = false;

        try {
            BUSCA_LISTA_PORTA = null;
            BUSCA_LISTA_PORTA = CommPortIdentifier.getPortIdentifiers();
            ID_Porta = null;

            while (ID_Porta == null && BUSCA_LISTA_PORTA.hasMoreElements()) {
                CommPortIdentifier PORTA_ATUAL = (CommPortIdentifier) BUSCA_LISTA_PORTA.nextElement();

                if (PORTA_ATUAL.getName().equals(serial_port) || PORTA_ATUAL.getName().startsWith(serial_port)) {
                    SERIAL_PORT = (SerialPort) PORTA_ATUAL.open(appName, TIME_OUT);

                    ID_Porta = PORTA_ATUAL;

                   // System.out.println("Conectado a porta : " + ID_Porta.getName());
                    //System.out.println("Velocidade : " + bauld_rate);
                    
                    JOptionPane.showMessageDialog(null, "Acomunicação foi feita com sucesso\n"+ ID_Porta.getName() );
                    JOptionPane.showMessageDialog(null, "Velocidade \n"+ + bauld_rate);
                    

                    break;

                }

            }
            
            SERIAL_PORT.setSerialPortParams(bauld_rate,SERIAL_PORT.DATABITS_8 , SERIAL_PORT.STOPBITS_1, SERIAL_PORT.PARITY_NONE);
            SERIAL_PORT.addEventListener(this);
            SERIAL_PORT.notifyOnDataAvailable(true);
            
            status = true;

            if (ID_Porta == null || SERIAL_PORT == null) {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            status = false;
        }
        return status;
    }
    
    public void enviaDados (String dados){
        try {
            output = SERIAL_PORT.getOutputStream();
            output.write(dados.getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }
    
    public synchronized void fechaSerial(){
    if(SERIAL_PORT != null){
        SERIAL_PORT.removeEventListener();
        SERIAL_PORT.close();
        JOptionPane.showMessageDialog(null, "Acomunicação foi enrreda com sucesso\n");
    }
    }
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comunica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comunica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comunica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comunica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comunica().setVisible(true);
            }
        });
    }

    @Override
    public void serialEvent(SerialPortEvent spe) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Conectar;
    private javax.swing.JButton btn_Desconectar;
    private javax.swing.JButton btn_Inicio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_Bauld_Rates;
    private javax.swing.JComboBox<String> jComboBox_Modelo_Placa;
    private javax.swing.JComboBox<String> jComboBox_Portas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Imagem_conexao;
    private javax.swing.JLabel lbl_Led_Status;
    private javax.swing.JTextField txt_Status;
    // End of variables declaration//GEN-END:variables
}
