/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPortEvent;
import gnu.io.*;
import gnu.io.SerialPortEventListener;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Enumeration;
import javax.sql.rowset.serial.SerialArray;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Principal extends javax.swing.JFrame implements SerialPortEventListener {

    ////////////////////////variaveis//////////////////////////
    private String[] PORT_NAME_LIST; // Retorna o nome das portas disponiveis 
    private Enumeration BUSCA_LISTA_PORTA; // Retorna a listas disponiveis no sistema 
    private CommPortIdentifier ID_Porta; // retorna o ID da porta
    private SerialPort SERIAL_PORT;
    private final String appName = "serialCNC";
    private final int TIME_OUT = 1000;
    private OutputStream output = null;
    private BufferedReader input = null;
    private String SERIAL_PORT_NAME;
    private int BAULD_RATES;
    private OutputStream serialOut;
    private String[] dado;
    private float a, b, c;
    private int ferram, profund;
    ///////////////////////////////////////////////////////////

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupForma = new javax.swing.ButtonGroup();
        lblSelecione = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRetangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btn6Lados = new javax.swing.JButton();
        btnRetanguloRaio = new javax.swing.JButton();
        btnElipse = new javax.swing.JButton();
        btn5Lados = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblDimensoes = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtC = new javax.swing.JFormattedTextField();
        txtB = new javax.swing.JFormattedTextField();
        txtA = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxFerramenta = new javax.swing.JComboBox<>();
        jSpinnerProfund = new javax.swing.JSpinner();
        jPanelMovimento = new javax.swing.JPanel();
        lblMovimento = new javax.swing.JLabel();
        btnYmais = new javax.swing.JButton();
        btnZmais = new javax.swing.JButton();
        btnXmenos = new javax.swing.JButton();
        btnXmais = new javax.swing.JButton();
        btnYmenos = new javax.swing.JButton();
        btnZmenos = new javax.swing.JButton();
        jPanelConexao = new javax.swing.JPanel();
        lblConexao = new javax.swing.JLabel();
        lblVelocidade = new javax.swing.JLabel();
        comboBox_Bauld_Rates = new javax.swing.JComboBox<>();
        lblPortas = new javax.swing.JLabel();
        comboBox_Portas = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Status = new javax.swing.JLabel();
        jPanel_trabalho = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Zerar = new javax.swing.JButton();
        txt_TrabX = new javax.swing.JLabel();
        txt_TrabY = new javax.swing.JLabel();
        txt_TrabZ = new javax.swing.JLabel();
        jPanel_Maquina = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_MaqX = new javax.swing.JLabel();
        txt_MaqY = new javax.swing.JLabel();
        txt_MaqZ = new javax.swing.JLabel();
        btn_referencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CNC Facil 0.1");

        lblSelecione.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSelecione.setText("Selecione a forma desejada");

        btnInicio.setBackground(new java.awt.Color(51, 255, 0));
        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setToolTipText("");
        btnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));

        btnPause.setBackground(new java.awt.Color(255, 255, 102));
        btnPause.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnPause.setText("Pause");
        btnPause.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));

        btnParar.setBackground(new java.awt.Color(255, 51, 51));
        btnParar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnParar.setText("Parar");
        btnParar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 51)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRetangulo.setBackground(new java.awt.Color(255, 255, 255));
        btnRetangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ret.png"))); // NOI18N
        btnRetangulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btnRetangulo);
        btnRetangulo.setMaximumSize(new java.awt.Dimension(250, 250));
        btnRetangulo.setMinimumSize(new java.awt.Dimension(250, 250));
        btnRetangulo.setPreferredSize(new java.awt.Dimension(250, 250));
        btnRetangulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RetS.png"))); // NOI18N
        btnRetangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetanguloMouseClicked(evt);
            }
        });
        btnRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloActionPerformed(evt);
            }
        });

        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cir.png"))); // NOI18N
        btnCirculo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btnCirculo);
        btnCirculo.setMaximumSize(new java.awt.Dimension(250, 250));
        btnCirculo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CirS.png"))); // NOI18N
        btnCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculoMouseClicked(evt);
            }
        });
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btn6Lados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6Lad.png"))); // NOI18N
        btn6Lados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btn6Lados);
        btn6Lados.setMaximumSize(new java.awt.Dimension(250, 250));
        btn6Lados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6LadS.png"))); // NOI18N
        btn6Lados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6LadosActionPerformed(evt);
            }
        });

        btnRetanguloRaio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RetRaio.png"))); // NOI18N
        btnRetanguloRaio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btnRetanguloRaio);
        btnRetanguloRaio.setMaximumSize(new java.awt.Dimension(250, 250));
        btnRetanguloRaio.setMinimumSize(new java.awt.Dimension(250, 250));
        btnRetanguloRaio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RetRaioS.png"))); // NOI18N
        btnRetanguloRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetanguloRaioActionPerformed(evt);
            }
        });

        btnElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Elip.png"))); // NOI18N
        btnElipse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btnElipse);
        btnElipse.setMaximumSize(new java.awt.Dimension(250, 250));
        btnElipse.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ElipS.png"))); // NOI18N
        btnElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElipseActionPerformed(evt);
            }
        });

        btn5Lados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5Lad.png"))); // NOI18N
        btn5Lados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroupForma.add(btn5Lados);
        btn5Lados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5LadS.png"))); // NOI18N
        btn5Lados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5LadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetanguloRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6Lados, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5Lados, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6Lados, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetanguloRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5Lados, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblA.setText("A");

        lblB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblB.setText("B");

        lblC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblC.setText("C");

        lblDimensoes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDimensoes.setText("Dimensões");

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 255, 0));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Profundidade:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Ferramenta:");

        jComboBoxFerramenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxFerramenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "5", "6", "8" }));

        jSpinnerProfund.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(41, 41, 41)
                .addComponent(btnOK)
                .addGap(66, 66, 66))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtA))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtC)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addComponent(lblDimensoes)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxFerramenta, 0, 80, Short.MAX_VALUE)
                            .addComponent(jSpinnerProfund))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDimensoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblC)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerProfund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnVoltar))
                .addGap(24, 24, 24))
        );

        jPanelMovimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMovimento.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblMovimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovimento.setText("Movimento Manual");

        btnYmais.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnYmais.setText("Y +");
        btnYmais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnZmais.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnZmais.setText("Z +");
        btnZmais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXmenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnXmenos.setText("X -");
        btnXmenos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnXmais.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnXmais.setText("X +");
        btnXmais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnYmenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnYmenos.setText("Y -");
        btnYmenos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnZmenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnZmenos.setText("Z -");
        btnZmenos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelMovimentoLayout = new javax.swing.GroupLayout(jPanelMovimento);
        jPanelMovimento.setLayout(jPanelMovimentoLayout);
        jPanelMovimentoLayout.setHorizontalGroup(
            jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMovimentoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnXmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXmais, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanelMovimentoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnYmais, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMovimentoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnZmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMovimentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZmais, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMovimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMovimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMovimentoLayout.setVerticalGroup(
            jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMovimentoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblMovimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYmais)
                    .addComponent(btnZmais))
                .addGap(18, 18, 18)
                .addGroup(jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXmais)
                    .addComponent(btnXmenos))
                .addGap(22, 22, 22)
                .addGroup(jPanelMovimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZmenos)
                    .addComponent(btnYmenos))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanelConexao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblConexao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblConexao.setText("Conexão");

        lblVelocidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblVelocidade.setText("Velocidade:");

        comboBox_Bauld_Rates.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPortas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPortas.setText("Portas:");

        comboBox_Portas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtStatus.setEditable(false);
        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 51, 51));
        txtStatus.setText("Desconectado");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar portas");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnConectar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnDesconectar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConexaoLayout = new javax.swing.GroupLayout(jPanelConexao);
        jPanelConexao.setLayout(jPanelConexaoLayout);
        jPanelConexaoLayout.setHorizontalGroup(
            jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConexaoLayout.createSequentialGroup()
                .addGroup(jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConexaoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnBuscar)
                        .addGap(101, 101, 101)
                        .addComponent(btnConectar)
                        .addGap(66, 66, 66)
                        .addComponent(btnDesconectar))
                    .addGroup(jPanelConexaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVelocidade)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox_Bauld_Rates, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConexao)
                            .addGroup(jPanelConexaoLayout.createSequentialGroup()
                                .addComponent(lblPortas)
                                .addGap(18, 18, 18)
                                .addComponent(comboBox_Portas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConexaoLayout.setVerticalGroup(
            jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConexaoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblConexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVelocidade)
                    .addComponent(comboBox_Bauld_Rates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPortas)
                    .addComponent(comboBox_Portas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnConectar)
                    .addComponent(btnDesconectar))
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado da Maquina");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Status:");

        txt_Status.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel_trabalho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Posição Trabalho:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Y:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Z:");

        btn_Zerar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Zerar.setText("Zerar Posição ");

        txt_TrabX.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txt_TrabY.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txt_TrabZ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel_trabalhoLayout = new javax.swing.GroupLayout(jPanel_trabalho);
        jPanel_trabalho.setLayout(jPanel_trabalhoLayout);
        jPanel_trabalhoLayout.setHorizontalGroup(
            jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                        .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TrabX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TrabZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                        .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_TrabY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_trabalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Zerar)
                .addGap(33, 33, 33))
        );
        jPanel_trabalhoLayout.setVerticalGroup(
            jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_trabalhoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TrabX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_TrabY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_trabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_TrabZ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_Zerar)
                .addContainerGap())
        );

        jPanel_Maquina.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Posição Maquina:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Y:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Z:");

        txt_MaqX.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txt_MaqY.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txt_MaqZ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btn_referencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_referencia.setText("Buscar Referecia");
        btn_referencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_referenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_MaquinaLayout = new javax.swing.GroupLayout(jPanel_Maquina);
        jPanel_Maquina.setLayout(jPanel_MaquinaLayout);
        jPanel_MaquinaLayout.setHorizontalGroup(
            jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addGroup(jPanel_MaquinaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MaqX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_MaquinaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MaqZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_MaquinaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MaqY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MaquinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_referencia)
                .addGap(20, 20, 20))
        );
        jPanel_MaquinaLayout.setVerticalGroup(
            jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MaquinaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_MaqX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_MaqY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_MaqZ, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btn_referencia)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel_trabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Maquina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_trabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSelecione))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelConexao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)
                                .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanelMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelecione)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPause)
                            .addComponent(btnParar))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloActionPerformed
        btnRetangulo.setSelected(true);
        btnCirculo.setEnabled(false);
        btn6Lados.setEnabled(false);
        btnRetanguloRaio.setEnabled(false);
        btnElipse.setEnabled(false);
        btn5Lados.setEnabled(false);
        txtC.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        comboBox_Portas.setModel(new DefaultComboBoxModel(new String[]{}));
        comboBox_Bauld_Rates.setModel(new DefaultComboBoxModel(new String[]{}));

        RetornaPortas();

        for (int i = 0; i < PORT_NAME_LIST.length; i++) {

            if (PORT_NAME_LIST[i] != null) {
                comboBox_Portas.addItem(PORT_NAME_LIST[i]);
                Bauld_Rates();

            }
            if (PORT_NAME_LIST[0] == null) {
                JOptionPane.showMessageDialog(null, "Nenhuma porta emcontrada!");
                break;
            }

        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:

        SERIAL_PORT_NAME = (String) (comboBox_Portas.getSelectedItem());
        BAULD_RATES = (int) (comboBox_Bauld_Rates.getSelectedIndex());

        //txtStatus.setText("Conectado");
        if (iniciaSerial(SERIAL_PORT_NAME, BAULD_RATES)) {

            txtStatus.setText("Conectado");
            txtStatus.setForeground(Color.green);

        }

    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:

        fechaSerial();

    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void btn_referenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_referenciaActionPerformed
        enviaDados("$H");

// TODO add your handling code here:
    }//GEN-LAST:event_btn_referenciaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        if (btnRetangulo.isSelected()) {

            try {
                a = Float.parseFloat(txtA.getValue().toString());
                b = Float.parseFloat(txtB.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                retangulo(a, b, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }
        }
        
        if (btnCirculo.isSelected()) {
            try {
                a = Float.parseFloat(txtA.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                circulo(a, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }            
        }
        if (btn6Lados.isSelected()) {
            try {
                a = Float.parseFloat(txtA.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                sextavado(a, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }
        }
        if (btnRetanguloRaio.isSelected()) {
            try {
                a = Float.parseFloat(txtA.getValue().toString());
                b = Float.parseFloat(txtB.getValue().toString());
                c = Float.parseFloat(txtC.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                retanguloRaio(a, b, c, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }
        }
        if (btnElipse.isSelected()) {
            try {
                a = Float.parseFloat(txtA.getValue().toString());
                b = Float.parseFloat(txtB.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                elipse(a, b, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }
        }
        if (btn5Lados.isSelected()) {
            try {
                a = Float.parseFloat(txtA.getValue().toString());

                ferram = Integer.parseInt(jComboBoxFerramenta.getSelectedItem().toString());
                profund = Integer.parseInt(jSpinnerProfund.getValue().toString());

                pentagono(a, ferram, profund);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Erro: " + e);
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnRetanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetanguloMouseClicked
        /*btnRetangulo.setSelected(true);
   btnCirculo.setEnabled(false);
   btn6Lados.setEnabled(false);
   btnRetanguloRaio.setEnabled(false);
   btnElipse.setEnabled(false);
   btn5Lados.setEnabled(false);*/

// TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloMouseClicked

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        btnRetangulo.setEnabled(false);
        btnCirculo.setSelected(true);
        btn6Lados.setEnabled(false);
        btnRetanguloRaio.setEnabled(false);
        btnElipse.setEnabled(false);
        btn5Lados.setEnabled(false);
        txtB.setEnabled(false);
        txtC.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseClicked
        /*btnRetangulo.setEnabled(false);
   btnCirculo.setSelected(true);
   btn6Lados.setEnabled(false);
   btnRetanguloRaio.setEnabled(false);
   btnElipse.setEnabled(false);
   btn5Lados.setEnabled(false);*/

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCirculoMouseClicked

    private void btn6LadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6LadosActionPerformed
        btnRetangulo.setEnabled(false);
        btnCirculo.setEnabled(false);
        btn6Lados.setSelected(true);
        btnRetanguloRaio.setEnabled(false);
        btnElipse.setEnabled(false);
        btn5Lados.setEnabled(false);
        txtB.setEnabled(false);
        txtC.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btn6LadosActionPerformed

    private void btnRetanguloRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetanguloRaioActionPerformed
        btnRetangulo.setEnabled(false);
        btnCirculo.setEnabled(false);
        btn6Lados.setEnabled(false);
        btnRetanguloRaio.setSelected(true);
        btnElipse.setEnabled(false);
        btn5Lados.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRetanguloRaioActionPerformed

    private void btnElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElipseActionPerformed
        btnRetangulo.setEnabled(false);
        btnCirculo.setEnabled(false);
        btn6Lados.setEnabled(false);
        btnRetanguloRaio.setEnabled(false);
        btnElipse.setSelected(true);
        btn5Lados.setEnabled(false);
        txtC.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnElipseActionPerformed

    private void btn5LadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5LadosActionPerformed
        btnRetangulo.setEnabled(false);
        btnCirculo.setEnabled(false);
        btn6Lados.setEnabled(false);
        btnRetanguloRaio.setEnabled(false);
        btnElipse.setEnabled(false);
        btn5Lados.setSelected(true);
        txtB.setEnabled(false);
        txtC.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5LadosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        btnRetangulo.setEnabled(true);
        btnCirculo.setEnabled(true);
        btn6Lados.setEnabled(true);
        btnRetanguloRaio.setEnabled(true);
        btnElipse.setEnabled(true);
        btn5Lados.setEnabled(true);

        txtA.setEnabled(true);
        txtB.setEnabled(true);
        txtC.setEnabled(true);

        btnRetangulo.setSelected(false);
        btnCirculo.setSelected(false);
        btn6Lados.setSelected(false);
        btnRetanguloRaio.setSelected(false);
        btnElipse.setSelected(false);
        btn5Lados.setSelected(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    //////////////////Funçoes //////////////////////////
    //Retorna portas disponiveis
    public String[] RetornaPortas() {
        int i = 0;

        BUSCA_LISTA_PORTA = null;
        BUSCA_LISTA_PORTA = CommPortIdentifier.getPortIdentifiers();
        PORT_NAME_LIST = new String[10];

        while (BUSCA_LISTA_PORTA.hasMoreElements()) {
            CommPortIdentifier PORTA_ATUAL = (CommPortIdentifier) BUSCA_LISTA_PORTA.nextElement();
            PORT_NAME_LIST[i] = PORTA_ATUAL.getName();
            i++;

        }

        return PORT_NAME_LIST;
    }

    private void Bauld_Rates() {
        comboBox_Bauld_Rates.addItem("300");
        comboBox_Bauld_Rates.addItem("1200");
        comboBox_Bauld_Rates.addItem("2400");
        comboBox_Bauld_Rates.addItem("9600");
        comboBox_Bauld_Rates.addItem("19200");
        comboBox_Bauld_Rates.addItem("38400");
        comboBox_Bauld_Rates.addItem("57600");
        comboBox_Bauld_Rates.addItem("115200");
        comboBox_Bauld_Rates.addItem("230400");
        comboBox_Bauld_Rates.addItem("250000");

    }

    public boolean iniciaSerial(String serial_port, int bauld_rate) {

        boolean status = false;

        try {
            BUSCA_LISTA_PORTA = null;
            BUSCA_LISTA_PORTA = CommPortIdentifier.getPortIdentifiers();
            ID_Porta = null;

            while (ID_Porta == null && BUSCA_LISTA_PORTA.hasMoreElements()) {
                CommPortIdentifier PORTA_ATUAL = (CommPortIdentifier) BUSCA_LISTA_PORTA.nextElement();

                if (PORTA_ATUAL.getName().equals(serial_port) || PORTA_ATUAL.getName().startsWith(serial_port)) {
                    SERIAL_PORT = (SerialPort) PORTA_ATUAL.open(appName, TIME_OUT);

                    ID_Porta = PORTA_ATUAL;

                    // System.out.println("Conectado a porta : " + ID_Porta.getName());
                    //System.out.println("Velocidade : " + bauld_rate);
                    //JOptionPane.showMessageDialog(null, "Acomunicação foi feita com sucesso\n"+ ID_Porta.getName() );
                    //JOptionPane.showMessageDialog(null, "Velocidade \n"+ + bauld_rate);
                    break;

                }

            }

            SERIAL_PORT.setSerialPortParams(bauld_rate, SERIAL_PORT.DATABITS_8, SERIAL_PORT.STOPBITS_1, SERIAL_PORT.PARITY_NONE);
            SERIAL_PORT.addEventListener(this);
            SERIAL_PORT.notifyOnDataAvailable(true);

            status = true;

            if (ID_Porta == null || SERIAL_PORT == null) {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            status = false;
        }
        return status;

    }

    public synchronized void fechaSerial() {
        if (SERIAL_PORT != null) {
            SERIAL_PORT.removeEventListener();
            SERIAL_PORT.close();
            JOptionPane.showMessageDialog(null, "Acomunicação foi enrreda com sucesso\n");
            txtStatus.setText("Desconectado");
            txtStatus.setForeground(Color.red);
        }

    }

    public void enviaDados(String dado) {

        String msg;
        msg = dado;

        try {

            //serialOut.write(dado.getBytes()); //escreve o valor na porta serial para ser enviado
            serialOut.write(msg.getBytes());
            serialOut.flush();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível enviar o dado. ",
                    "Enviar dados", JOptionPane.PLAIN_MESSAGE);
        }
    }
    //retangulo
    public void retangulo(float a, float b, int ferram, int profund) {

        JOptionPane.showMessageDialog(null, "Retangulo de: " + a + "mm x " + b + "mm\n" +" Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        FileWriter arquivo;
   
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--RETANGULO DE " + a + "mm x " + b + "mm%n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X" + ((a/2+(ferram)+10)*-1) + " Y" + ((b/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        gravarArq.printf("G1 X" + ((a/2+(ferram/2))*-1) + "%n");
                        gravarArq.printf("G1 Y" + (b/2+(ferram/2)) + "%n");
                        gravarArq.printf("G1 X" + (a/2+(ferram/2)) + "%n");
                        gravarArq.printf("G1 Y" + ((b/2+(ferram/2))*-1) + "%n");
                        gravarArq.printf("G1 X" + ((a/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G1 Y" + ((b/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
        

    }
    
    //Circulo
    public void circulo(float a, int ferram, int profund) {

        JOptionPane.showMessageDialog(null, "Circulo de: " + a + "mm de Diametro \n" + " Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        FileWriter arquivo;
   
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--CIRCULO DE " + a + "mm DE DIAMTRO%n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X0" + " Y" + ((a/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        gravarArq.printf("G1 Y" + ((a/2+(ferram/2))*-1)  + "%n");
                        gravarArq.printf("G2 X0 Y" + ((a/2+(ferram/2))*-1) + "I0 J" + (a/2+(ferram/2)) + "%n");
                        gravarArq.printf("G1 Y" + ((a/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

    }
    
    //Sextavado
    public void sextavado(float a, int ferram, int profund) {

        JOptionPane.showMessageDialog(null, "Sextavado de: " + a + " Diametro \n" +" Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        
        FileWriter arquivo;
        
        float a1, b1, a2, a3, a4, a5;
        
        a1 = a+(ferram/2); //RAIO PARA A
        //b1 = ((b+ferram)/2); //RAIO PARA B
        a2 = 0; //ÂNGULO INICIAL
        a3 = 361; //ÂNGULO FINAL
        a4 = 1; //INCREMENTO ANGULAR
        a5 = 10; //DIST. SEGURANÇA       
        
        
        
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--Sextavado DE " + a + "mm de Diametro %n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a2)))) + " Y" + ((a1+a5)*(Math.sin(Math.toRadians(a2)))) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        while (a3>a2){
                        gravarArq.printf("G1 X" + (a1*(Math.cos(Math.toRadians(a2)))) + " Y" + (a1*(Math.sin(Math.toRadians(a2)))) + "%n");
                        a2 = a2 + 60;
                        }
                        gravarArq.printf("G1 X" + ((a1)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((a1)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((a1+a5)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
        
        
        

    }
    
    //Pentagono
    public void pentagono(float a, int ferram, int profund) {

                JOptionPane.showMessageDialog(null, "Pentágono  de: " + a + " Diametro \n" +" Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        
        FileWriter arquivo;
        
        float a1, b1, a2, a3, a4, a5;
        
        a1 = a+(ferram/2); //RAIO PARA A
        //b1 = ((b+ferram)/2); //RAIO PARA B
        a2 = 0; //ÂNGULO INICIAL
        a3 = 360; //ÂNGULO FINAL
        a4 = 1; //INCREMENTO ANGULAR
        a5 = 10; //DIST. SEGURANÇA       
        
        
        
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--Pentágono  DE " + a + "mm de Diametro %n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a2)))) + " Y" + ((a1+a5)*(Math.sin(Math.toRadians(a2)))) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        while (a3>a2){
                        gravarArq.printf("G1 X" + (a1*(Math.cos(Math.toRadians(a2)))) + " Y" + (a1*(Math.sin(Math.toRadians(a2)))) + "%n");
                        a2 = a2 + 72;
                        }
                        gravarArq.printf("G1 X" + ((a1)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((a1)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((a1+a5)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

    }
    
    //retangulo Raio
    public void retanguloRaio(float a, float b, float c, int ferram, int profund) {

        JOptionPane.showMessageDialog(null, "Retangulo de: " + a + "mm x " + b + "mm\n" + "Raio de:" + c +" Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        FileWriter arquivo;
   
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--RETANGULO DE " + a + "mm x " + b + "mm%n");
                        gravarArq.printf(";--COM RAIO DE " + c + "mm%n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X0" + " Y" + ((b/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        gravarArq.printf("G1 Y" + ((b/2+(ferram/2))*-1)  + "%n");
                        gravarArq.printf("G1 X" + ((a/2+(ferram/2))*-1) + " R" + c + "%n");
                        gravarArq.printf("G1 Y" + (b/2+(ferram/2)) + " R" + c + "%n");
                        gravarArq.printf("G1 X" + (a/2+(ferram/2)) + " R" + c + "%n");
                        gravarArq.printf("G1 Y" + ((b/2+(ferram/2))*-1) + " R" + c + "%n");
                        gravarArq.printf("G1 X0%n");
                        gravarArq.printf("G0 X0" + " Y" + ((b/2+(ferram)+10)*-1) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

    }
    
    //Elipse
    public void elipse(float a, float b, int ferram, int profund) {

        JOptionPane.showMessageDialog(null, "Elipse de: " + a + "mm x " + b + "mm\n" +" Ferramenta de: " 
                + ferram + "mm - Profundidade de: " + profund + "mm");
        
        
        FileWriter arquivo;
        
        float a1, b1, a2, a3, a4, a5;
        
        a1 = ((a+ferram)/2); //RAIO PARA A
        b1 = ((b+ferram)/2); //RAIO PARA B
        a2 = 0; //ÂNGULO INICIAL
        a3 = 361; //ÂNGULO FINAL
        a4 = 1; //INCREMENTO ANGULAR
        a5 = 10; //DIST. SEGURANÇA       
        
        
        
		try {
			arquivo = new FileWriter(new File("D:\\Teste.cnc"));
                        PrintWriter gravarArq = new PrintWriter(arquivo);

                        gravarArq.printf(";--ELIPSE DE " + a + "mm x " + b + "mm%n");
                        gravarArq.printf(";--PROFUNDIDADE DE " + profund + "mm%n");
                        gravarArq.printf(";--FERRAMENTA DE " + ferram + "mm de Diametro%n");
                        gravarArq.printf(";---------------------------------------------%n");
                        gravarArq.printf("G90 G17 G54%n");
                        gravarArq.printf("F1000%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("G0 X0 Y0%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a2)))) + " Y" + ((b1+a5)*(Math.sin(Math.toRadians(a2)))) + "%n");
                        gravarArq.printf("G1 Z" + profund + "%n");
                        while (a3>a2){
                        gravarArq.printf("G1 X" + (a1*(Math.cos(Math.toRadians(a2)))) + " Y" + (b1*(Math.sin(Math.toRadians(a2)))) + "%n");
                        a2++;
                        }
                        gravarArq.printf("G1 X" + ((a1)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((b1)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 X" + ((a1+a5)*(Math.cos(Math.toRadians(a3)))) + " Y" + ((b1+a5)*(Math.sin(Math.toRadians(a3)))) + "%n");
                        gravarArq.printf("G0 Z100%n");
                        gravarArq.printf("M30%n");
			arquivo.close();
                        
		} catch (IOException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}

    }

    ///////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn5Lados;
    private javax.swing.JButton btn6Lados;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnElipse;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnRetangulo;
    private javax.swing.JButton btnRetanguloRaio;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnXmais;
    private javax.swing.JButton btnXmenos;
    private javax.swing.JButton btnYmais;
    private javax.swing.JButton btnYmenos;
    private javax.swing.JButton btnZmais;
    private javax.swing.JButton btnZmenos;
    private javax.swing.JButton btn_Zerar;
    private javax.swing.JButton btn_referencia;
    public javax.swing.ButtonGroup buttonGroupForma;
    private javax.swing.JComboBox<String> comboBox_Bauld_Rates;
    private javax.swing.JComboBox<String> comboBox_Portas;
    private javax.swing.JComboBox<String> jComboBoxFerramenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelConexao;
    private javax.swing.JPanel jPanelMovimento;
    private javax.swing.JPanel jPanel_Maquina;
    private javax.swing.JPanel jPanel_trabalho;
    private javax.swing.JSpinner jSpinnerProfund;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblConexao;
    private javax.swing.JLabel lblDimensoes;
    private javax.swing.JLabel lblMovimento;
    private javax.swing.JLabel lblPortas;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblVelocidade;
    private javax.swing.JFormattedTextField txtA;
    private javax.swing.JFormattedTextField txtB;
    private javax.swing.JFormattedTextField txtC;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JLabel txt_MaqX;
    private javax.swing.JLabel txt_MaqY;
    private javax.swing.JLabel txt_MaqZ;
    private javax.swing.JLabel txt_Status;
    private javax.swing.JLabel txt_TrabX;
    private javax.swing.JLabel txt_TrabY;
    private javax.swing.JLabel txt_TrabZ;
    // End of variables declaration//GEN-END:variables

    @Override
    public void serialEvent(SerialPortEvent spe) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
